import 'package:flutter/material.dart';

class JobData {
  String name;
  String logo;
  String city;
  String role;
  String eligibility;
  String stipend;
  String applyLink;

  JobData({required this.name, required this.city , required this.role,required this.logo,required this.eligibility ,required this.stipend ,required this.applyLink});
  

  Map<String,String> toJson(){
    return {
      'name':"${this.name}",
          'logo':"${this.logo}",
          'city':"${this.city}",
          'role':"${this.role}",
          'eligibility':"${this.eligibility}",
          'stipend':"${this.stipend}",
          'applyLink':"${this.applyLink}",
          
    };
  }

}

// List<JobData> data=
//           [
//               JobData(
//     name: "Tata Consultancy Services (TCS)",
//     logo: "https://example.com/logos/tcs.png",
//     city: "Ahamdabad",
//     role: "Flutter Developer",
//     eligibility: "B.E. / B.Tech / MCA with 1+ years of experience in Dart & Flutter. Minimum 6.0 CGPA required.",
//     stipend: "₹45,000/mo",
//     applyLink: "https://careers.tcs.com/jobs/flutter-dev-ahamdabad",
//   ),
//    JobData(
//     name: "Reliance Industries Ltd.",
//     logo: "https://example.com/logos/reliance.png",
//     city: "Jamnager",
//     role: "Operations Maintenance Engineer",
//     eligibility: "Diploma or B.Tech in Mechanical / Electrical Engineering. Freshers welcome with a minimum of 6.5 CGPA.",
//     stipend: "₹60,000/mo",
//     applyLink: "https://jal.reliance.com/careers/ops-eng-jamnagar",
//   ),
//    JobData(
//     name: "Infosys",
//     logo: "https://example.com/logos/infosys.png",
//     city: "Rajkot",
//     role: "UI/UX Designer",
//     eligibility: "Bachelor's degree in Design/Fine Arts or portfolio showing Figma mastery. Must maintain 6.0 CGPA or above.",
//     stipend: "₹35,000/mo",
//     applyLink: "https://careers.infosys.com/jobs/uiux-rajkot",
//   ),
//    JobData(
//     name: "Surat Diamond Software Corp",
//     logo: "https://example.com/logos/sdsc.png",
//     city: "Surat",
//     role: "Backend Engineer (Node.js)",
//     eligibility: "2+ years experience with Node.js and MongoDB. Open to graduates with 7.0+ CGPA.",
//     stipend: "₹50,000/mo",
//     applyLink: "https://sdsc.in/careers/backend-node-surat",
//   ),
//    JobData(
//     name: "Adani Group",
//     logo: "https://example.com/logos/adani.png",
//     city: "Kutch",
//     role: "Logistics & Supply Chain Executive",
//     eligibility: "MBA in Supply Chain Management or 2 years experience. Minimum 6.0 CGPA in post-graduation.",
//     stipend: "₹42,000/mo",
//     applyLink: "https://adani.com/careers/logistics-kutch",
//   ),
//    JobData(
//     name: "WebWave Technologies",
//     logo: "https://example.com/logos/webwave.png",
//     city: "Ahamdabad",
//     role: "Frontend React Developer",
//     eligibility: "Strong knowledge of JavaScript and React.js. Strict cut-off of 7.0 CGPA for freshers.",
//     stipend: "₹30,000/mo",
//     applyLink: "https://webwave.io/join-us/react-ahmd",
//   ),
//    JobData(
//     name: "Maruti Techlabs",
//     logo: "https://example.com/logos/maruti.png",
//     city: "Ahamdabad",
//     role: "AI / QA Automation Engineer",
//     eligibility: "Experience writing test scripts in Python. 6.5 CGPA and above with no active backlogs.",
//     stipend: "₹38,000/mo",
//     applyLink: "https://marutitech.com/careers/qa-automation",
//   ),
//    JobData(
//     name: "Wipro",
//     logo: "https://example.com/logos/wipro.png",
//     city: "Ahamdabad",
//     role: "Cloud Infrastructure Engineer",
//     eligibility: "B.Tech/MCA with AWS or Azure certification. Requires a baseline of 6.0 CGPA throughout academics.",
//     stipend: "₹40,000/mo",
//     applyLink: "https://careers.wipro.com/jobs/cloud-ahmd",
//   ),
//    JobData(
//     name: "Cognizant",
//     logo: "https://example.com/logos/cognizant.png",
//     city: "Rajkot",
//     role: "Data Analyst",
//     eligibility: "Bachelor's degree in Statistics or CS. Proficiency in SQL. 6.5 CGPA tier requirement.",
//     stipend: "₹35,000/mo",
//     applyLink: "https://careers.cognizant.com/global/data-analyst-rajkot",
//   ),
//    JobData(
//     name: "Larsen & Toubro (L&T)",
//     logo: "https://example.com/logos/lnt.png",
//     city: "Surat",
//     role: "Structural Design Engineer",
//     eligibility: "M.Tech in Structural Engineering. Outstanding academic track record with 7.5+ CGPA preferred.",
//     stipend: "₹55,000/mo",
//     applyLink: "https://lntecc.com/careers/structural-surat",
//   ),
//    JobData(
//     name: "Essar Ports",
//     logo: "https://example.com/logos/essar.png",
//     city: "Kutch",
//     role: "Harbor Operations Supervisor",
//     eligibility: "Degree in Marine Engineering or Logistics. Technical minimum 6.0 CGPA criteria.",
//     stipend: "₹48,000/mo",
//     applyLink: "https://essar.com/careers/harbor-ops-kutch",
//   ),
//    JobData(
//     name: "Nayara Energy",
//     logo: "https://example.com/logos/nayara.png",
//     city: "Jamnager",
//     role: "Chemical Process Engineer",
//     eligibility: "B.Tech in Chemical Engineering. Strong refinery chemistry foundation and 7.0+ CGPA requirement.",
//     stipend: "₹52,000/mo",
//     applyLink: "https://nayaraenergy.com/careers/chemical-jamnagar",
//   ),
//    JobData(
//     name: "HCLTech",
//     logo: "https://example.com/logos/hcl.png",
//     city: "Ahamdabad",
//     role: "Cybersecurity Specialist",
//     eligibility: "CEH or CISSP certification. Experience with firewalls. B.Tech Graduate with minimum 6.5 CGPA.",
//     stipend: "₹46,000/mo",
//     applyLink: "https://www.hcltech.com/careers/cybersec-ahmd",
//   ),
//    JobData(
//     name: "Techops Solutions",
//     logo: "https://example.com/logos/techops.png",
//     city: "Rajkot",
//     role: "PHP Laravel Developer",
//     eligibility: "1-3 years experience with MVC architecture and MySQL. Degree threshold set at 5.5 CGPA.",
//     stipend: "₹28,000/mo",
//     applyLink: "https://techops.io/careers/laravel-dev",
//   ),
//    JobData(
//     name: "Goldi Solar",
//     logo: "https://example.com/logos/goldisolar.png",
//     city: "Surat",
//     role: "Solar PV Plant Engineer",
//     eligibility: "B.E. Electrical. Experience in design of commercial solar systems. Grade criteria: 6.0+ CGPA.",
//     stipend: "₹32,000/mo",
//     applyLink: "https://goldisolar.com/careers/pv-engineer",
//   ),
//    JobData(
//     name: "Welspun Group",
//     logo: "https://example.com/logos/welspun.png",
//     city: "Kutch",
//     role: "Plant HR Manager",
//     eligibility: "MBA in Human Resources with 5+ years handling industrial labor relations. 6.0 CGPA constraint in post-graduation.",
//     stipend: "₹65,000/mo",
//     applyLink: "https://welspun.com/careers/hr-manager-kutch",
//   ),
//    JobData(
//     name: "DigiScale Media",
//     logo: "https://example.com/logos/digiscale.png",
//     city: "Jamnager",
//     role: "SEO & Content Marketing Executive",
//     eligibility: "Excellent English writing skills and experience with SEMrush. Open to any graduate holding 5.5+ CGPA.",
//     stipend: "₹22,000/mo",
//     applyLink: "https://digiscalemedia.in/careers/seo-exec",
//   ),
//    JobData(
//     name: "Capgemini",
//     logo: "https://example.com/logos/capgemini.png",
//     city: "Ahamdabad",
//     role: "DevOps Engineer",
//     eligibility: "Hands-on experience with Docker, Kubernetes, and CI/CD pipelines. Baseline criteria of 6.5 CGPA.",
//     stipend: "₹44,000/mo",
//     applyLink: "https://capgemini.com/careers/devops-ahmd",
//   ),
//    JobData(
//     name: "Tech Mahindra",
//     logo: "https://example.com/logos/techm.png",
//     city: "Rajkot",
//     role: "Technical Support Associate",
//     eligibility: "Any graduate with good communication skills. Minimum 5.0 CGPA standard rule applies.",
//     stipend: "₹25,000/mo",
//     applyLink: "https://techmahindra.com/careers/techsupport-rajkot",
//   ),
//    JobData(
//     name: "Kiran Gems",
//     logo: "https://example.com/logos/kirangems.png",
//     city: "Surat",
//     role: "Inventory & Logistics Officer",
//     eligibility: "B.Com/BBA graduate with advanced Excel skills. Academic history must reflect a 6.0+ CGPA.",
//     stipend: "₹27,000/mo",
//     applyLink: "https://kirangems.com/careers/logistics-officer",
//   ),
//   JobData(
//     name: "Adani Green Energy",
//     logo: "https://example.com/logos/adanigreen.png",
//     city: "Kutch",
//     role: "Site Safety Inspector",
//     eligibility: "Diploma in Industrial Safety. Field experience on renewable sites required. 6.0 CGPA standard.",
//     stipend: "₹34,000/mo",
//     applyLink: "https://adanigreen.com/careers/safety-kutch",
//   ),
//    JobData(
//     name: "RapidWeb Labs",
//     logo: "https://example.com/logos/rapidweb.png",
//     city: "Jamnager",
//     role: "Full Stack Node/React Developer",
//     eligibility: "Freshers with solid final year projects. Development aptitude is prioritized along with a 6.5+ CGPA threshold.",
//     stipend: "₹30,000/mo",
//     applyLink: "https://rapidweblabs.com/careers/fullstack-jam",
//   ),
//    JobData(
//     name: "Cygnet Digital",
//     logo: "https://example.com/logos/cygnet.png",
//     city: "Ahamdabad",
//     role: "Angular Frontend Developer",
//     eligibility: "2+ years writing modular TypeScript code. Graduation scorecard must show 6.0 CGPA or more.",
//     stipend: "₹42,000/mo",
//     applyLink: "https://cygnet-digital.com/careers/angular-dev",
//   ),
//    JobData(
//     name: "Emperor Software",
//     logo: "https://example.com/logos/emperor.png",
//     city: "Rajkot",
//     role: "Android (Kotlin) Developer",
//     eligibility: "Strong knowledge of Android SDK, Room Database, and Coroutines. Must clear tech rounds and have a 6.5+ CGPA background.",
//     stipend: "₹36,000/mo",
//     applyLink: "https://emperorsoft.com/jobs/android-kotlin",
//   ),
//    JobData(
//     name: "Anupam Rasayan India Ltd.",
//     logo: "https://example.com/logos/anupam.png",
//     city: "Surat",
//     role: "R&D Lab Chemist",
//     eligibility: "M.Sc in Organic Chemistry. Experience operating HPLC machinery. Post-graduation score must match 7.0+ CGPA requirement.",
//     stipend: "₹40,000/mo",
//     applyLink: "https://anupamrasayan.com/careers/rd-chemist",
//   ),
//    JobData(
//     name: "Mundra Port Logistics",
//     logo: "https://example.com/logos/mundraport.png",
//     city: "Kutch",
//     role: "Customs Documentation Specialist",
//     eligibility: "Knowledge of import/export laws and custom clearance procedures. Any graduate with a 6.0 CGPA base setup.",
//     stipend: "₹31,000/mo",
//     applyLink: "https://mundraport.com/careers/customs-spec",
//   ),
//    JobData(
//     name: "Jio Platforms",
//     logo: "https://example.com/logos/jio.png",
//     city: "Jamnager",
//     role: "Network Field Engineer",
//     eligibility: "B.Tech in Electronics & Telecommunications. Fiber-optic troubleshooting skillsets. Cut-off criteria: 6.5 CGPA.",
//     stipend: "₹33,000/mo",
//     applyLink: "https://careers.jio.com/jobs/network-field-jamnagar",
//   ),
//           ];